import type { Locale,ReportPayload,RespondentRole,TriadReport } from "./types";
import { text } from "./types";
export function escapeHtml(value:unknown):string{return String(value??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[c]!);}
export const respondentLabel=(role:RespondentRole,locale:Locale)=>({student:locale==="zh-HK"?"學生自評":"学生自评",parent:locale==="zh-HK"?"家長觀察":"家长观察",teacher:locale==="zh-HK"?"教師觀察":"教师观察"})[role];
function triadReportHtml(p:ReportPayload,locale:Locale):string{
  const report=p.triad as TriadReport;
  const hk=locale==="zh-HK",t=(cn:string,tw=cn)=>hk?tw:cn,e=escapeHtml;
  const fmt=(iso:string)=>new Intl.DateTimeFormat(locale,{timeZone:"Asia/Hong_Kong",year:"numeric",month:"long",day:"numeric"}).format(new Date(iso));
  const roleName=(role:RespondentRole)=>role==="student"?t("孩子","孩子"):role==="parent"?t("家长","家長"):t("老师","老師");
  const sources=report.sources.map(source=>`${e(roleName(source.role))} ${e(fmt(source.submittedAt))}`).join(" · ");
  const safety=report.safety.length?`<section class="risk"><h2>${e(t("请先关注安全","請先關注安全"))}</h2>${report.safety.map(message=>`<p>${e(text(message,locale))}</p>`).join("")}<p>${e(t("报告仍然发给家长。工作人员也会同时看到安全提示。如有眼前危险，请联系当地紧急服务。","報告仍然發給家長。工作人員也會同時看到安全提示。如有眼前危險，請聯絡當地緊急服務。"))}</p></section>`:"";
  const domains=report.domains.map(domain=>`<section class="dimension"><h3>${e(text(domain.label,locale))}</h3>${domain.note?`<p class="band">${e(text(domain.note,locale))}</p>`:""}${domain.views.map(view=>`<p><strong>${e(text(view.label,locale))}</strong> ${e(text(view.body,locale))}</p>`).join("")}</section>`).join("");
  const portrait=report.portrait.length?`<section class="portrait"><h2>${e(t("家长通常会怎样处理","家長通常會怎樣處理"))}</h2><p class="meta">${e(t("这里用平实的话描述您自己的回答，不给家长打分，也不划分等级。","這裏用平實的話描述您自己的回答，不給家長打分，也不劃分等級。"))}</p>${report.portrait.map(item=>`<p><strong>${e(text(item.heading,locale))}</strong> ${e(text(item.body,locale))}</p>`).join("")}</section>`:"";
  const situations=report.situations.length?`<section class="situations"><h2>${e(t("遇到这些情况时，各方通常会怎么做","遇到這些情況時，各方通常會怎麼做"))}</h2><p class="meta">${e(t("情境题不记入分数，只用来看实际会怎么处理。","情境題不計入分數，只用來看實際會怎麼處理。"))}</p>${report.situations.map(item=>`<p><strong>${e(roleName(item.role))}</strong> ${e(text(item.prompt,locale))}</p><p>${e(text(item.choice,locale))}</p>`).join("")}</section>`:"";
  const priorities=report.priorities.length?`<section class="priorities"><h2>${e(t("这次最希望得到的帮助","這次最希望得到的幫助"))}</h2>${report.priorities.map(item=>`<p><strong>${e(roleName(item.role))}</strong> ${e(text(item.prompt,locale))}</p><p>${e(item.choices.map(choice=>text(choice,locale)).join("、"))}</p>`).join("")}</section>`:"";
  const words=report.words.length?`<section class="words"><h2>${e(t("他们写下的话","他們寫下的話"))}</h2>${report.words.map(item=>`<p><strong>${e(roleName(item.role))} · ${e(text(item.prompt,locale))}</strong></p><p>${e(item.value)}</p>`).join("")}</section>`:"";
  return `<!DOCTYPE html><html lang="${locale}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${e(text(report.title,locale))} · Nova</title><style>
  *{box-sizing:border-box}body{margin:0;background:#f4f7f4;color:#243833;font:16px/1.75 "PingFang SC","PingFang HK","Hiragino Sans GB","Noto Sans SC","Noto Sans CJK SC","Microsoft YaHei",sans-serif;text-autospace:normal}article{max-width:760px;margin:32px auto;padding:56px 64px;background:#ffffff;border:1px solid #dde6e0}header{border-bottom:1px solid #dde6e0;padding-bottom:28px}.brand{font-family:"Songti SC","Songti TC","Noto Serif SC","PMingLiU",serif;font-size:22px;letter-spacing:-0.03em;color:#2c6058;font-weight:560}h1{font-family:"Songti SC","Songti TC","Noto Serif SC","PMingLiU",serif;font-size:34px;line-height:1.35;margin:18px 0 14px;font-weight:560;color:#243833}h2{font-family:"Songti SC","Songti TC","Noto Serif SC","PMingLiU",serif;font-size:22px;margin:32px 0 12px;font-weight:560;color:#243833}h3{font-size:16px;margin:0 0 8px}.meta{font-size:12px;color:#526860}.risk{padding:18px 20px;background:#fff0ed;border:1px solid #e9b8ae;border-radius:6px}.risk h2{margin:0 0 8px;color:#9b4039}.dimension,.portrait,.situations,.priorities,.words{border:0;border-top:1px solid #dde6e0;border-radius:0;padding:20px 0;margin:0}p{margin:8px 0}.band{color:#526860}.limitation{font-size:12px;color:#526860}footer{margin-top:30px;padding-top:18px;border-top:1px solid #dde6e0;font-size:11px;color:#526860}
  @page{size:A4;margin:14mm 14mm 18mm}@media print{body{background:#fff}article{margin:0;padding:0}}
  </style></head><body><article><header><div class="brand">nova</div><h1>${e(text(report.title,locale))}</h1><p>${e(p.childName)} · ${e(p.grade)}</p><p class="meta">${sources}</p><p>${e(t("这份报告把孩子、家长和老师各自的回答放在一起读。它不合成一个总分，也不做诊断。三方看到的不一样时，先把它当成不同情境里的观察。","這份報告把孩子、家長和老師各自的回答放在一起讀。它不合成一個總分，也不做診斷。三方看到的不一樣時，先把它當成不同情境裏的觀察。"))}</p></header>
  ${safety}<h2>${e(t("三方看到的情况","三方看到的情況"))}</h2>${domains||`<p>${e(t("这几个方面的有效回答还不够，这里先不概括。","這幾個方面的有效回答還不夠，這裏先不概括。"))}</p>`}${portrait}${situations}${priorities}${words}
  <p class="limitation">${e(text(p.template.content.limitation,locale))}</p><footer>Nova Psycho Helper · ${e(t("三份都交齐后自动生成。家庭私密报告，请妥善保管。","三份都交齊後自動產生。家庭私密報告，請妥善保管。"))}</footer></article></body></html>`;
}
export function reportHtml(p:ReportPayload,locale:Locale):string{
  if(p.triad)return triadReportHtml(p,locale);
  const hk=locale==="zh-HK",t=(cn:string,tw=cn)=>hk?tw:cn,e=escapeHtml;
  const fmt=(iso:string)=>new Intl.DateTimeFormat(locale,{timeZone:"Asia/Hong_Kong",year:"numeric",month:"long",day:"numeric"}).format(new Date(iso));
  const date=fmt(p.submittedAt);
  const advice=p.selectedAdviceIds.map(id=>p.advice.content.blocks.find(b=>b.id===id)).filter(b=>b!==undefined);
  const nextStep=p.score.risk?t("请优先帮助孩子获得安全、可信任的成人及专业支持。如有眼前危险，请联系当地紧急服务。普通家庭建议不能替代对即时安全问题的处理。","請優先幫助孩子獲得安全、可信任的成人及專業支持。如有眼前危險，請聯絡當地緊急服務。普通家庭建議不能替代對即時安全問題的處理。"):advice.length?text(p.template.content.nextStep,locale):t("先确认量表是否适用，以及哪些必要信息尚未完成，再决定是否补充作答。当前资料不足的部分暂不解释。","先確認量表是否適用，以及哪些必要資料尚未完成，再決定是否補充作答。目前資料不足的部分暫不解釋。");
  const dimensions=p.score.dimensions.map(d=>{
    const ratio=d.raw===null?0:Math.max(0,Math.min(100,100*(d.raw-d.min)/(d.max-d.min||1)));
    return `<section class="dimension"><div class="dim-head"><h3>${e(text(d.label,locale))}</h3><span class="score">${d.raw===null?"—":e(d.raw)} <small>/ ${e(d.max)}</small></span></div><div class="meter"><span style="width:${ratio}%"></span></div><p class="band">${e(d.band?text(d.band.label,locale):t("资料不足，暂不解释","資料不足，暫不解釋"))}</p><p>${e(d.band?text(d.band.explanation,locale):t("本维度缺少必要答案，系统没有补零或推测得分。","本維度缺少必要答案，系統沒有補零或推測得分。"))}</p><p class="meta">${e(t("已回答","已回答"))} ${d.answered}/${d.totalItems}${d.prorated?` · ${e(t("按本量表规则折算","按本量表規則折算"))}`:""} · ${e(t("原始分数，非人群百分位","原始分數，非人群百分位"))}</p></section>`;
  }).join("");
  const higherMeaning=(means:"more_support"|"more_strength")=>means==="more_support"?t("分数越高表示需要更多支持。","分數越高表示需要更多支持。"):t("分数越高表示该方面的优势更明显。","分數越高表示該方面的優勢更明顯。");
  const rawChange=(delta:number)=>delta>0?t("原始分较上次升高","原始分較上次升高"):delta<0?t("原始分较上次降低","原始分較上次降低"):t("原始分较上次没有变化","原始分較上次沒有變化");
  const comparison=p.comparison.available?`<div class="comparison">${p.comparison.previousDate?`<p class="meta">${e(t("对比的上次测评日期","對比的上次測評日期"))} ${e(fmt(p.comparison.previousDate))}</p>`:""}${p.comparison.changes!.map(c=>`<p><strong>${e(text(c.label,locale))}</strong> ${e(rawChange(c.delta))} · ${e(t("较上次原始分变化","較上次原始分變化"))} <strong>${c.delta>0?"+":""}${e(c.delta)}</strong></p><p class="meta">${e(higherMeaning(c.higherMeans))}</p>`).join("")}<p class="meta">${e(t("仅比较相同填答者与相同量表版本。变化本身不证明辅导疗效。","僅比較相同填答者與相同量表版本。變化本身不證明輔導療效。"))}</p></div>`:`<p>${e(t("目前没有适合直接比较的同版本、同填答者记录。不同填答者的观察分别保留，不计算合并总分。","目前沒有適合直接比較的同版本、同填答者紀錄。不同填答者的觀察分別保留，不計算合併總分。"))}</p>`;
  return `<!DOCTYPE html><html lang="${locale}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${e(text(p.template.content.title,locale))} · Nova</title><style>
  *{box-sizing:border-box}body{margin:0;background:#f4f7f4;color:#243833;font:16px/1.75 "PingFang SC","PingFang HK","Hiragino Sans GB","Noto Sans SC","Noto Sans CJK SC","Microsoft YaHei",sans-serif;text-autospace:normal}article{max-width:760px;margin:32px auto;padding:56px 64px;background:#ffffff;border:1px solid #dde6e0}header{border-bottom:1px solid #dde6e0;padding-bottom:28px}.brand{font-family:"Songti SC","Songti TC","Noto Serif SC","PMingLiU",serif;font-size:22px;letter-spacing:-0.03em;color:#2c6058;font-weight:560}.brand small{font-size:12px;letter-spacing:0.12em;margin-left:10px;color:#526860;font-weight:500}h1{font-family:"Songti SC","Songti TC","Noto Serif SC","PMingLiU",serif;font-size:34px;line-height:1.35;margin:18px 0 14px;font-weight:560;color:#243833}h2{font-family:"Songti SC","Songti TC","Noto Serif SC","PMingLiU",serif;font-size:22px;margin:32px 0 12px;font-weight:560;color:#243833}h3{font-size:16px;margin:0}.intro{color:#526860}.meta{font-size:12px;color:#526860}.demo{padding:14px 16px;background:#f8efe4;color:#6a4a28;border:1px solid #eadcc8;border-radius:10px;margin:24px 0;font-size:14px}.risk{padding:18px 20px;background:#fff0ed;border:1px solid #e9b8ae;border-radius:6px;break-inside:avoid}.risk h2{margin:0 0 8px;color:#9b4039}.dimension{border:0;border-top:1px solid #dde6e0;border-radius:0;padding:20px 0;margin:0;break-inside:avoid}.dim-head{display:flex;justify-content:space-between;align-items:center}.score{font-family:"Songti SC","Songti TC","Noto Serif SC","PMingLiU",serif;font-size:24px;font-weight:560}.score small{font-size:13px;color:#526860}.meter{height:2px;background:#dde6e0;margin:14px 0;border-radius:99px;overflow:hidden}.meter span{display:block;height:100%;background:#2c6058}.band{font-size:13px;color:#526860;margin-bottom:4px}.dimension p{margin-top:8px;margin-bottom:0}.advice{border-top:1px solid #e4e9e4;padding:17px 0;break-inside:avoid}.advice p{margin:8px 0}.next{background:#f4f7f4;border-radius:12px;padding:20px 24px;break-inside:avoid}.next h2{margin:0 0 8px}.next p{margin:0}.comparison{border-top:1px solid #dde6e0;padding-top:16px}footer{margin-top:30px;padding-top:18px;border-top:1px solid #dde6e0;font-size:11px;color:#526860}.limitation{font-size:12px;color:#526860}.facts{display:flex;gap:10px 24px;flex-wrap:wrap;font-size:13px;color:#526860}.empty{padding:18px;background:#f4f7f4;border-radius:10px}
  @media(max-width:600px){article{margin:0;padding:26px 22px}h1{font-size:25px}.facts{gap:8px 16px}.brand small{display:block;margin:0}}@page{size:A4;margin:14mm 14mm 18mm} @media print{body{background:#fff;font-size:11px;line-height:1.7}article{max-width:none;margin:0;padding:0}h1{font-size:24px}h2{font-size:15px;margin-top:22px}h3{font-size:13px}.dimension{padding:13px 16px}.score{font-size:20px}.demo{font-size:10px;margin:16px 0}.advice{padding:12px 0}.meta,.limitation{font-size:10px}.facts{font-size:11px}footer{font-size:10px}.brand{font-size:18px}}
  </style></head><body><article><header><div class="brand">nova <small>PSYCHO HELPER</small></div><h1>${e(text(p.template.content.title,locale))}</h1><div class="facts"><span>${e(p.childName)}</span><span>${e(p.grade)}</span><span>${e(respondentLabel(p.score.respondentRole,locale))}</span><span>${e(date)}</span></div><p class="intro">${e(text(p.template.content.introduction,locale))}</p></header>
  ${p.score.demo?`<div class="demo"><strong>${e(t("演示报告 · 使用虚构题目与合成数据","示範報告 · 使用虛構題目與合成資料"))}</strong><br>${e(t("本示例没有临床常模，不代表任何真实孩子的心理健康评估结果。","本示例沒有臨床常模，不代表任何真實孩子的心理健康評估結果。"))}</div>`:""}
  ${p.score.risk?`<section class="risk"><h2>${e(t("请先关注安全","請先關注安全"))}</h2>${p.score.riskMessages.map(m=>`<p>${e(text(m,locale))}</p>`).join("")}</section>`:""}
  ${p.score.status!=="valid"?`<p class="empty">${e(t("本次资料不完整。可以查看已具备必要答案的维度；未完成的部分不作结论。","本次資料不完整。可以查看已具備必要答案的維度；未完成的部分不作結論。"))}</p>`:""}
  <h2>${e(t("理解这一次的观察","理解這一次的觀察"))}</h2><p class="meta">${e(text(p.scale.title,locale))} · ${e(text(p.score.norm.label,locale))}</p>${dimensions}
  <h2>${e(t("家长可以尝试的下一步","家長可以嘗試的下一步"))}</h2>${advice.length?advice.map((b,i)=>`<section class="advice"><h3>${i+1}. ${e(text(b.title,locale))}</h3><p>${e(text(b.body,locale))}</p><p class="meta">${e(t("依据维度","依據維度"))}：${e(b.dimensionKeys.map(key=>p.score.dimensions.find(d=>d.key===key)).filter(Boolean).map(d=>text(d!.label,locale)).join("、"))} · ${e(b.source)}</p></section>`).join(""):`<p>${e(t("资料不足，暂不生成个性化建议。可以先与服务人员一起确认测评是否完整。","資料不足，暫不生成個人化建議。可以先與服務人員一起確認測評是否完整。"))}</p>`}
  <h2>${e(t("和上一次相比","和上一次相比"))}</h2>${comparison}
  <section class="next"><h2>${e(p.score.risk?t("先获得适合的支持","先獲得適合的支持"):t("把理解带回日常","把理解帶回日常"))}</h2><p>${e(nextStep)}</p></section>
  <p class="limitation">${e(text(p.template.content.limitation,locale))}</p><footer>Nova Psycho Helper · ${e(t("家庭私密报告，请妥善保管","家庭私密報告，請妥善保管"))}<br>${e(t("量表版本","量表版本"))} ${e(p.scale.version)} · ${e(t("建议库","建議庫"))} ${e(p.advice.version)} · ${e(t("报告模板","報告模板"))} ${e(p.template.version)} · ${e(p.generationMode==="ai"?t("AI 辅助组织建议，规则计分，自动发布","AI 輔助組織建議，規則計分，自動發佈"):t("专业规则模板，自动发布","專業規則模板，自動發佈"))}</footer></article></body></html>`;
}
