import type { Locale,ReportPayload,RespondentRole } from "./types";
import { text } from "./types";
export function escapeHtml(value:unknown):string{return String(value??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[c]!);}
export const respondentLabel=(role:RespondentRole,locale:Locale)=>({student:locale==="zh-HK"?"學生自評":"学生自评",parent:locale==="zh-HK"?"家長觀察":"家长观察",teacher:locale==="zh-HK"?"教師觀察":"教师观察"})[role];
export function reportHtml(p:ReportPayload,locale:Locale):string{
  const hk=locale==="zh-HK",t=(cn:string,tw=cn)=>hk?tw:cn,e=escapeHtml;
  const fmt=(iso:string)=>new Intl.DateTimeFormat(locale,{timeZone:"Asia/Hong_Kong",year:"numeric",month:"long",day:"numeric"}).format(new Date(iso));
  const date=fmt(p.submittedAt);
  const advice=p.selectedAdviceIds.map(id=>p.advice.content.blocks.find(b=>b.id===id)).filter(b=>b!==undefined);
  const nextStep=p.score.risk?t("请优先帮助孩子获得安全、可信任的成人及专业支持。如有眼前危险，请联系当地紧急服务。普通家庭建议不能替代对即时安全问题的处理。","請優先幫助孩子獲得安全、可信任的成人及專業支持。如有眼前危險，請聯絡當地緊急服務。普通家庭建議不能替代對即時安全問題的處理。"):advice.length?text(p.template.content.nextStep,locale):t("先确认量表是否适用，以及哪些必要信息尚未完成，再决定是否补充作答。当前资料不足的部分暂不解释。","先確認量表是否適用，以及哪些必要資料尚未完成，再決定是否補充作答。目前資料不足的部分暫不解釋。");
  const dimensions=p.score.dimensions.map(d=>{
    const ratio=d.raw===null?0:Math.max(0,Math.min(100,100*(d.raw-d.min)/(d.max-d.min||1)));
    return `<section class="dimension"><div class="dim-head"><h3>${e(text(d.label,locale))}</h3><span class="score">${d.raw===null?"—":e(d.raw)} <small>/ ${e(d.max)}</small></span></div><div class="meter"><span style="width:${ratio}%"></span></div><p class="band">${e(d.band?text(d.band.label,locale):t("资料不足，暂不解释","資料不足，暫不解釋"))}</p><p>${e(d.band?text(d.band.explanation,locale):t("本维度缺少必要答案，系统没有补零或推测得分。","本維度缺少必要答案，系統沒有補零或推測得分。"))}</p><p class="meta">${e(t("已回答","已回答"))} ${d.answered}/${d.totalItems}${d.prorated?` · ${e(t("按本量表规则折算","按本量表規則折算"))}`:""} · ${e(t("原始分数，非人群百分位","原始分數，非人群百分位"))}</p></section>`;
  }).join("");
  const higherMeaning=(means:"more_support"|"more_strength")=>means==="more_support"?t("分数越高表示需要更多支持。","分數越高表示需要更多支持。"):t("分数越高表示该方面的优势更明显。","分數越高表示該方面的優勢更明顯。");
  const rawChange=(delta:number)=>delta>0?t("原始分较上次升高","原始分較上次升高"):delta<0?t("原始分较上次降低","原始分較上次降低"):t("原始分较上次没有变化","原始分較上次沒有變化");
  const comparison=p.comparison.available?`<div class="comparison">${p.comparison.previousDate?`<p class="meta">${e(t("对比的上次测评日期","對比的上次測評日期"))} ${e(fmt(p.comparison.previousDate))}</p>`:""}${p.comparison.changes!.map(c=>`<p><strong>${e(text(c.label,locale))}</strong> ${e(rawChange(c.delta))} · ${e(t("较上次原始分变化","較上次原始分變化"))} <strong>${c.delta>0?"+":""}${e(c.delta)}</strong></p><p class="meta">${e(higherMeaning(c.higherMeans))}</p>`).join("")}<p class="meta">${e(t("仅比较相同填答者与相同量表版本。变化本身不证明辅导疗效。","僅比較相同填答者與相同量表版本。變化本身不證明輔導療效。"))}</p></div>`:`<p>${e(t("目前没有适合直接比较的同版本、同填答者记录。不同填答者的观察分别保留，不计算合并总分。","目前沒有適合直接比較的同版本、同填答者紀錄。不同填答者的觀察分別保留，不計算合併總分。"))}</p>`;
  return `<!DOCTYPE html><html lang="${locale}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${e(text(p.template.content.title,locale))} · Nova</title><style>
  *{box-sizing:border-box}body{margin:0;background:#f2f4ef;color:#243b34;font:15px/1.85 "PingFang SC","PingFang HK","Noto Sans CJK SC","Noto Sans CJK TC",Arial,sans-serif}article{max-width:850px;margin:24px auto;padding:48px 56px;background:white}header{border-bottom:1px solid #dce5df;padding-bottom:24px}.brand{font-size:21px;letter-spacing:1px;color:#2e6757;font-weight:600}.brand small{font-size:11px;letter-spacing:2px;margin-left:10px}h1{font-size:30px;line-height:1.4;margin:20px 0 12px;font-weight:600}h2{font-size:19px;margin:30px 0 14px;color:#244c40}h3{font-size:16px;margin:0}.intro{color:#536d60}.meta{font-size:12px;color:#697e72}.demo{padding:12px 16px;background:#fff5e6;color:#755427;border-left:3px solid #ceac70;margin:24px 0;font-size:13px}.risk{padding:18px 20px;background:#fff0ed;border:1px solid #e9b8ae;border-radius:6px;break-inside:avoid}.risk h2{margin:0 0 8px;color:#9b4039}.dimension{border:1px solid #dce5df;border-radius:8px;padding:20px 22px;margin-bottom:14px;break-inside:avoid}.dim-head{display:flex;justify-content:space-between;align-items:center}.score{font-size:24px;font-weight:600}.score small{font-size:13px;color:#77857d}.meter{height:5px;background:#ebefeb;margin:14px 0;border-radius:8px;overflow:hidden}.meter span{display:block;height:100%;background:#6b9c85}.band{font-size:13px;color:#416e59;margin-bottom:4px}.dimension p{margin-top:8px;margin-bottom:0}.advice{border-top:1px solid #e4e9e4;padding:17px 0;break-inside:avoid}.advice p{margin:8px 0}.next{background:#edf3ec;border-radius:8px;padding:20px 24px;break-inside:avoid}.next h2{margin:0 0 8px}.next p{margin:0}.comparison{border-left:3px solid #92b29d;padding-left:18px}footer{margin-top:30px;padding-top:18px;border-top:1px solid #dce5df;font-size:11px;color:#6a7b70}.limitation{font-size:12px;color:#687b6e}.facts{display:flex;gap:10px 24px;flex-wrap:wrap;font-size:13px;color:#5d7265}.empty{padding:18px;background:#f6f6f0}
  @media(max-width:600px){article{margin:0;padding:26px 22px}h1{font-size:25px}.facts{gap:8px 16px}.brand small{display:block;margin:0}}@page{size:A4;margin:14mm 14mm 18mm} @media print{body{background:#fff;font-size:11px;line-height:1.7}article{max-width:none;margin:0;padding:0}h1{font-size:24px}h2{font-size:15px;margin-top:22px}h3{font-size:13px}.dimension{padding:13px 16px}.score{font-size:20px}.demo{font-size:10px;margin:16px 0}.advice{padding:12px 0}.meta,.limitation{font-size:9px}.facts{font-size:10px}footer{font-size:8px}.brand{font-size:18px}}
  </style></head><body><article><header><div class="brand">nova <small>PSYCHO HELPER</small></div><h1>${e(text(p.template.content.title,locale))}</h1><div class="facts"><span>${e(p.childName)}</span><span>${e(p.grade)}</span><span>${e(respondentLabel(p.score.respondentRole,locale))}</span><span>${e(date)}</span></div><p class="intro">${e(text(p.template.content.introduction,locale))}</p></header>
  ${p.score.demo?`<div class="demo"><strong>${e(t("演示报告 · 使用虚构题目与合成数据","示範報告 · 使用虛構題目與合成資料"))}</strong><br>${e(t("本示例没有临床常模，不代表任何真实孩子的心理健康评估结果。","本示例沒有臨床常模，不代表任何真實孩子的心理健康評估結果。"))}</div>`:""}
  ${p.score.risk?`<section class="risk"><h2>${e(t("请先关注安全","請先關注安全"))}</h2>${p.score.riskMessages.map(m=>`<p>${e(text(m,locale))}</p>`).join("")}</section>`:""}
  ${p.score.status!=="valid"?`<p class="empty">${e(t("本次资料不完整。可以查看已具备必要答案的维度；未完成的部分不作结论。","本次資料不完整。可以查看已具備必要答案的維度；未完成的部分不作結論。"))}</p>`:""}
  <h2>${e(t("理解这一次的观察","理解這一次的觀察"))}</h2><p class="meta">${e(text(p.scale.title,locale))} · ${e(text(p.score.norm.label,locale))}</p>${dimensions}
  <h2>${e(t("家长可以尝试的下一步","家長可以嘗試的下一步"))}</h2>${advice.length?advice.map((b,i)=>`<section class="advice"><h3>${i+1}. ${e(text(b.title,locale))}</h3><p>${e(text(b.body,locale))}</p><p class="meta">${e(t("依据维度","依據維度"))}：${e(b.dimensionKeys.map(key=>p.score.dimensions.find(d=>d.key===key)).filter(Boolean).map(d=>text(d!.label,locale)).join("、"))} · ${e(b.source)}</p></section>`).join(""):`<p>${e(t("资料不足，暂不生成个性化建议。可以先与服务人员一起确认测评是否完整。","資料不足，暫不生成個人化建議。可以先與服務人員一起確認測評是否完整。"))}</p>`}
  <h2>${e(t("和上一次相比","和上一次相比"))}</h2>${comparison}
  <section class="next"><h2>${e(p.score.risk?t("先获得适合的支持","先獲得適合的支持"):t("把理解带回日常","把理解帶回日常"))}</h2><p>${e(nextStep)}</p></section>
  <p class="limitation">${e(text(p.template.content.limitation,locale))}</p><footer>Nova Psycho Helper · ${e(t("家庭私密报告，请妥善保管","家庭私密報告，請妥善保管"))}<br>${e(t("量表版本","量表版本"))} ${e(p.scale.version)} · ${e(t("建议库","建議庫"))} ${e(p.advice.version)} · ${e(t("报告模板","報告模板"))} ${e(p.template.version)} · ${e(p.generationMode==="ai"?t("AI 辅助组织建议，规则计分，自动发布","AI 輔助組織建議，規則計分，自動發佈"):t("专业规则模板，自动发布","專業規則模板，自動發佈"))}</footer></article></body></html>`;
}
