"use client";
import { useEffect, useState } from "react";
import { ArrowRight, CheckCircle, CircleNotch, IconContext, LockKey } from "@phosphor-icons/react";
import { api, ApiError, errorMessage, type Region, type Role, type Session } from "@/components/api";
import { formatDate, roleName } from "@/components/copy";
import { useLinkToken } from "@/components/link-token";
import { Brand, ErrorNotice, Field, Loading, LocaleSwitch, useLocale, useMutation } from "@/components/ui";

interface RecoverySummary { name: string; username: string; role: Role; region: Region; expiresAt: string }

// Reached from a single-use link an administrator issued. The link is read from the
// URL fragment so it never reaches the server in a referrer or access log, matching
// the invitation flow. Completing this does not create a session; the account holder
// signs in afterwards with the new password.
export default function RecoverPage() {
  const { locale, setLocale, t } = useLocale(); const { token, generation, isCurrent } = useLinkToken(); const [recovery, setRecovery] = useState<RecoverySummary | null>(null); const [error, setError] = useState(""); const [done, setDone] = useState(false); const [clerkRecovery, setClerkRecovery] = useState(false); const [mismatch, setMismatch] = useState(false); const m = useMutation(); const [attempt, setAttempt] = useState(0);
  useEffect(() => { setRecovery(null); setDone(false); setClerkRecovery(false); setMismatch(false); m.setError(""); }, [token, generation, m.setError]);
  useEffect(() => { if (token === null) return; if (!token) { setError(t("noRecoveryToken")); return; } const controller = new AbortController(); setError(""); api<RecoverySummary>("/api/recovery", locale, { signal: controller.signal, headers: { "X-Recovery-Token": token } }).then(value => { if (!controller.signal.aborted) setRecovery(value); }).catch(err => { if (!controller.signal.aborted) { if (err instanceof ApiError && err.code === "CLERK_RECOVERY_REQUIRED") setClerkRecovery(true); else setError(errorMessage(err)); } }); api<Session>("/api/session", locale, { signal: controller.signal }).then(value => { if (value.region === "HK" && !localStorage.getItem("nova-locale")) setLocale("zh-HK"); }).catch(() => undefined); return () => controller.abort(); }, [token, generation, locale, attempt]);
  return <IconContext.Provider value={{ size: 20, weight: "regular" }}><main className="invite-page"><header className="login-header"><Brand /><div className="login-header-tools"><LocaleSwitch locale={locale} onChange={setLocale} /></div></header><section className="invite-card"><div className="login-card-icon"><LockKey size={28} weight="regular" /></div><span className="eyebrow">{t("recovery")}</span><h1>{t("recoveryTitle")}</h1>{clerkRecovery ? <><p>{t("clerkRecoveryRequired")}</p><a className="button primary full-width" href="/sign-in">{t("emailLogin")}<ArrowRight /></a></> : error ? <ErrorNotice message={error} locale={locale} onRetry={token ? () => setAttempt(attempt + 1) : undefined} /> : done ? <><p className="body-copy">{t("recoveryDone")}</p><a className="button primary full-width" href="/">{t("goToLogin")}<ArrowRight /></a></> : !recovery ? <Loading locale={locale} /> : <><p>{t("recoveryWelcome")}</p><div className="invite-summary"><strong>{recovery.name}</strong><span>{recovery.username} · {roleName(recovery.role, locale)}</span><small>{t("expires")} {formatDate(recovery.expiresAt, locale, true)}</small></div><form onSubmit={event => { event.preventDefault(); const data = new FormData(event.currentTarget); const password = String(data.get("password") ?? ""); if (password !== String(data.get("confirm") ?? "")) { setMismatch(true); return; } setMismatch(false); void m.run(async () => { try { await api("/api/recovery", locale, { method: "POST", body: { token, password } }); if (isCurrent()) setDone(true); } catch (error) { if (isCurrent()) { if (error instanceof ApiError && error.code === "CLERK_RECOVERY_REQUIRED") { setRecovery(null); setClerkRecovery(true); } else throw error; } } }); }}><Field label={t("setNewPassword")} hint={t("passwordHint")}><input name="password" type="password" autoComplete="new-password" required minLength={12} /></Field><Field label={t("confirmPassword")}><input name="confirm" type="password" autoComplete="new-password" required minLength={12} /></Field>{mismatch && <ErrorNotice message={t("passwordMismatch")} locale={locale} />}{m.error && <ErrorNotice message={m.error} locale={locale} />}<button className="button primary full-width" disabled={m.busy}>{m.busy ? <CircleNotch className="spin" /> : <CheckCircle />}{t(m.busy ? "saving" : "setNewPassword")}</button></form></>}</section></main></IconContext.Provider>;
}
