import type { Locale, Role, AssessmentStatus } from "./api";
// Exported so tests can assert that every entry carries both locales.
export const dictionary = {
  brand: ["Nova 心理助手", "Nova 心理助手"], tagline: ["看见成长，陪伴每一步", "看見成長，陪伴每一步"],
  dashboard: ["工作台", "工作台"], families: ["家庭档案", "家庭檔案"], assessments: ["测评任务", "評估任務"], reports: ["成长报告", "成長報告"], care: ["关怀计划", "關懷計劃"], scales: ["量表库", "量表庫"], content: ["报告内容", "報告內容"], workspace: ["家庭支持工作空间", "家庭支援工作空間"],
  loading: ["正在载入…", "正在載入…"], retry: ["重新载入", "重新載入"], retryReport: ["重新排队生成报告", "重新排隊產生報告"], retrying: ["正在重新排队…", "正在重新排隊…"], retryQueued: ["报告已重新排队，生成完成后会自动更新。", "報告已重新排隊，產生完成後會自動更新。"], close: ["关闭", "關閉"], cancel: ["取消", "取消"], save: ["保存", "儲存"], saving: ["正在保存…", "正在儲存…"], saved: ["已保存", "已儲存"], create: ["创建", "建立"], creating: ["正在创建…", "正在建立…"], submit: ["确认提交", "確認提交"], submitting: ["正在提交…", "正在提交…"], back: ["返回", "返回"], viewAll: ["查看全部", "查看全部"], view: ["查看", "查看"], search: ["搜索家庭、学生姓名", "搜尋家庭、學生姓名"], refresh: ["刷新", "重新整理"], actions: ["操作", "操作"],
  login: ["登录工作空间", "登入工作空間"], loginIntro: ["让每一次了解，成为更好的陪伴。", "讓每一次了解，成為更好的陪伴。"], username: ["用户名", "用戶名稱"], password: ["密码", "密碼"], passwordHint: ["至少 12 个字符", "至少 12 個字元"], loginButton: ["登录", "登入"], loggingIn: ["正在登录…", "正在登入…"], logout: ["退出登录", "登出"], demoAccounts: ["选择一个演示账户", "選擇一個示範帳戶"], demoAccountNote: ["以下均为合成账户；正式服务使用独立账户登录。", "以下均為合成帳戶；正式服務使用獨立帳戶登入。"],
  demo: ["演示数据", "示範資料"], demoNotice: ["演示工作空间 · 所有人物、家庭及结果均为合成示例，不用于实际心理判断。", "示範工作空間 · 所有人物、家庭及結果均為合成例子，不用於實際心理判斷。"], demoScale: ["演示量表", "示範量表"], service: ["正式服务", "正式服務"], regionCN: ["中国内地独立站", "中國內地獨立站"], regionHK: ["香港独立站", "香港獨立站"], otherRegion: ["前往另一独立站", "前往另一獨立站"], regionNotice: ["语言切换仅改变显示语言，不会切换地区或迁移数据。", "語言切換只改變顯示語言，不會切換地區或遷移資料。"], language: ["界面语言", "介面語言"], privacy: ["隐私与知情同意", "私隱與知情同意"], privacyShort: ["隐私说明", "私隱說明"],
  welcome: ["欢迎回来", "歡迎回來"], welcomeSub: ["从了解开始，让关怀持续发生。", "從了解開始，讓關懷持續發生。"], today: ["工作概览", "工作概覽"], familyCount: ["服务家庭", "服務家庭"], pendingCount: ["待完成测评", "待完成評估"], reportCount: ["已生成报告", "已產生報告"], goalCount: ["进行中关怀目标", "進行中關懷目標"], scope: ["仅统计当前账户获授权的数据", "只統計目前帳戶獲授權的資料"], yourFamilies: ["正在陪伴的家庭", "正在陪伴的家庭"], familySub: ["把每一份关注，落实在日常的支持中。", "把每一份關注，落實在日常的支援中。"], tasksTitle: ["接下来，做一点小事", "接下來，做一點小事"], tasksSub: ["待完成的测评任务", "待完成的評估任務"], noPending: ["目前没有待完成的测评", "目前沒有待完成的評估"], noPendingText: ["新的测评分配后，会显示在这里。", "新的評估獲分配後，會顯示在這裏。"], latestReports: ["最近的成长报告", "最近的成長報告"], automatic: ["提交后自动生成", "提交後自動產生"], automaticNote: ["报告由服务自动生成，完成后授权成人可直接查看。", "報告由服務自動產生，完成後獲授權成人可直接查看。"], everyday: ["把关心，变成可行动的小目标", "把關心，變成可行動的小目標"], careNote: ["与家庭一起记录下一步，也看见已经做到的改变。", "與家庭一起記錄下一步，也看見已經做到的改變。"],
  newFamily: ["新增家庭", "新增家庭"], family: ["家庭", "家庭"], child: ["学生姓名", "學生姓名"], familyName: ["家庭名称", "家庭名稱"], birthDate: ["出生日期", "出生日期"], age: ["年龄", "年齡"], years: ["岁", "歲"], grade: ["年级", "年級"], guardian: ["监护人姓名", "監護人姓名"], staff: ["负责同事", "負責同事"], unassigned: ["暂不指定", "暫不指定"], consentStatus: ["知情同意", "知情同意"], consented: ["已记录同意", "已記錄同意"], noConsent: ["待取得同意", "待取得同意"], familyEmpty: ["还没有家庭档案", "還沒有家庭檔案"], familyEmptyText: ["完成建档并取得监护人同意后，即可安排测评。", "完成建檔並取得監護人同意後，即可安排評估。"], noSearch: ["没有找到匹配的家庭", "沒有找到符合條件的家庭"], details: ["查看档案", "查看檔案"], authorizedMembers: ["已授权家庭成员", "已授權家庭成員"], noMembers: ["暂无关联成员", "暫無關聯成員"], consentTitle: ["记录监护人知情同意", "記錄監護人知情同意"], consentNote: ["请先阅读隐私说明，了解测评、报告生成和数据处理方式。", "請先閱讀私隱說明，了解評估、報告產生及資料處理方式。"], consentCheck: ["我已阅读隐私说明，同意为此家庭开展测评及生成报告。", "我已閱讀私隱說明，同意為此家庭進行評估及產生報告。"], offlineRef: ["已签署线下同意书的存档编号", "已簽署線下同意書的存檔編號"], offlineNote: ["工作人员须已有监护人签署的线下同意记录，并填写可核验的存档编号。", "工作人員須已有監護人簽署的線下同意記錄，並填寫可核實的存檔編號。"], directConsent: ["记录方式：监护人在线同意", "記錄方式：監護人網上同意"], offlineConsent: ["记录方式：工作人员录入已签署的线下同意", "記錄方式：工作人員輸入已簽署的線下同意"], consentSaved: ["知情同意已记录。", "知情同意已記錄。"],
  draftConflictTitle: ["检测到更新的草稿", "偵測到更新的草稿"],
  draftConflictNote: ["已暂停自动保存和最终提交。请先记录本页修改，再载入最新草稿；重新载入会用最新保存的回答替换本页内容。", "已暫停自動儲存和最終提交。請先記錄本頁修改，再載入最新草稿；重新載入會以最新儲存的回答取代本頁內容。"],
  localDraftAnswers: ["本页回答（可复制留存）", "本頁回答（可複製留存）"],
  copyDraftAnswers: ["复制本页回答", "複製本頁回答"],
  draftCopyFailed: ["无法自动复制，请选择本页回答并手动复制。", "無法自動複製，請選取本頁回答並手動複製。"],
  reloadLatestDraft: ["重新载入最新草稿", "重新載入最新草稿"],
  firstVersionTitle: ["创建第一个内容版本", "建立第一個內容版本"],
  firstVersionNote: ["此类内容尚未配置。下方仅提供空白 JSON 结构，请填写适合服务用途的专业内容后再保存。空白字段无法通过验证。", "此類內容尚未配置。下方只提供空白 JSON 結構，請填寫適合服務用途的專業內容後再儲存。空白欄位無法通過驗證。"],
  adviceStructureHelp: ["title 填写建议库名称。blocks 中填写 id、title、body、source；dimensionKeys 应匹配相应量表的维度。每个语言字段都需填写简体和繁体中文。", "title 填寫建議庫名稱。blocks 中填寫 id、title、body、source；dimensionKeys 應配對相應量表的維度。每個語言欄位都須填寫簡體和繁體中文。"],
  templateStructureHelp: ["填写 title、introduction、limitation、nextStep；每个字段都需包含简体和繁体中文内容。请说明报告用途、解读限制和下一步支持。", "填寫 title、introduction、limitation、nextStep；每個欄位都須包含簡體和繁體中文內容。請說明報告用途、解讀限制和下一步支援。"],
  noVersions: ["尚无已保存版本", "尚無已儲存版本"],
  saveFirstVersion: ["保存第一个版本", "儲存第一個版本"],
  usernameHint: ["3–100 个字符，可使用英文字母、数字及 _ . @ -", "3–100 個字元，可使用英文字母、數字及 _ . @ -"],
  assentFirst: ["请先阅读并确认以下说明，确认后可开始或继续作答，草稿会自动保存。", "請先閱讀並確認以下說明，確認後可開始或繼續作答，草稿會自動儲存。"],
  aiConsent: ["可选：我同意使用结构化测评结果进行 AI 辅助报告处理。", "可選：我同意使用結構化評估結果進行 AI 輔助報告處理。"], aiConsentNote: ["不同意此可选项仍可使用测评服务，并生成规则模板报告。", "不同意此可選項仍可使用評估服務，並產生規則範本報告。"],
  invite: ["邀请成员", "邀請成員"], inviteNote: ["为关联家庭的成员创建邀请链接，再由你安全分享。", "為關聯家庭的成員建立邀請連結，再由你安全分享。"], createInvite: ["生成邀请链接", "產生邀請連結"], copy: ["复制链接", "複製連結"], copied: ["已复制", "已複製"], copyFailed: ["无法自动复制，请选择链接并手动复制。", "無法自動複製，請選取連結並手動複製。"], expires: ["有效期至", "有效期至"], inviteLink: ["邀请链接", "邀請連結"],
  deleteData: ["删除家庭数据", "刪除家庭資料"], deleteTitle: ["确认删除家庭数据", "確認刪除家庭資料"], deleteWarning: ["这会删除该家庭及相关测评、报告、关怀记录和私有文件。此操作不可恢复。", "這會刪除該家庭及相關評估、報告、關懷記錄和私人檔案。此操作無法復原。"], confirmName: ["请输入学生姓名以确认", "請輸入學生姓名以確認"], deleteButton: ["永久删除", "永久刪除"],
  newAssessment: ["安排测评", "安排評估"], respondent: ["作答人", "作答人"], chooseFamily: ["选择家庭", "選擇家庭"], chooseMember: ["选择已关联成员", "選擇已關聯成員"], chooseScale: ["选择量表版本", "選擇量表版本"], scaleVersion: ["量表版本", "量表版本"], noEligibleScale: ["该成员的身份或学生年龄暂无适用的有效量表。", "該成員的身分或學生年齡暫無適用的有效量表。"], retakeNote: ["系统会核验量表适用范围及重复测评间隔。", "系統會核實量表適用範圍及重複評估間隔。"], consentNeeded: ["请先记录监护人知情同意。", "請先記錄監護人知情同意。"], taskList: ["测评任务", "評估任務"], taskIntro: ["分配清晰，进度可见；完成后自动生成报告。", "分配清晰，進度可見；完成後自動產生報告。"], respondentIntro: ["这里是分配给你的测评。按自己的真实感受作答即可。", "這裏是分配給你的評估。按自己的真實感受作答即可。"], start: ["开始作答", "開始作答"], continue: ["继续作答", "繼續作答"], submitted: ["已完成提交", "已完成提交"], submittedNote: ["谢谢你的参与。你的回答已提交，无需再次填写。", "謝謝你的參與。你的回答已提交，無需再次填寫。"], noTasks: ["暂无测评任务", "暫無評估任務"], taskAssigned: ["测评已安排。指定成员登录后可完成作答。", "評估已安排。指定成員登入後可完成作答。"], assignedDate: ["安排日期", "安排日期"], reportQueued: ["报告正在生成", "報告正在產生"], reportFailed: ["报告生成失败，请联系工作人员。", "報告產生失敗，請聯絡工作人員。"], pendingHelp: ["等待指定成员完成作答", "等待指定成員完成作答"], questionnaire: ["填写测评", "填寫評估"], answerNotice: ["请按最近的真实情况作答，没有标准答案。草稿会自动保存。", "請按最近的真實情況作答，沒有標準答案。草稿會自動儲存。"], acknowledge: ["我已了解测评说明与隐私说明，自愿提交本次回答。", "我已了解評估說明與私隱說明，自願提交本次回答。"], acknowledgeNeeded: ["请先确认测评与隐私说明。", "請先確認評估與私隱說明。"], checkAnswers: ["请完成所有必答题后提交。", "請完成所有必答題後提交。"], unsaved: ["有未保存的更改", "有未儲存的變更"], saveFailed: ["草稿保存失败，请重试或保持页面打开。", "草稿儲存失敗，請重試或保持頁面開啟。"], saveDraft: ["保存草稿", "儲存草稿"], savedDraft: ["草稿已保存", "草稿已儲存"],
  reportIntro: ["从结果到行动，为日常陪伴提供参考。", "從結果到行動，為日常陪伴提供參考。"], noReports: ["暂无已生成报告", "暫無已產生報告"], noReportsText: ["测评提交后，报告将在这里自动更新。", "評估提交後，報告會在這裏自動更新。"], viewReport: ["查看报告", "查看報告"], downloadPdf: ["下载 PDF", "下載 PDF"], generated: ["生成日期", "產生日期"], aiReport: ["AI 辅助生成", "AI 輔助產生"], templateReport: ["规则模板生成", "規則範本產生"], risk: ["建议关注", "建議關注"], resultReference: ["报告用于支持沟通与关怀，不构成临床诊断。", "報告用於支援溝通與關懷，不構成臨床診斷。"], reportDocument: ["成长报告正文", "成長報告內文"],
  newGoal: ["添加关怀目标", "新增關懷目標"], goalTitle: ["目标名称", "目標名稱"], goalDetail: ["具体行动", "具體行動"], active: ["进行中", "進行中"], completed: ["已完成", "已完成"], markComplete: ["标记完成", "標記完成"], reopen: ["重新开启", "重新開啟"], noGoals: ["还没有关怀目标", "還沒有關懷目標"], goalPlaceholder: ["例如：每天留出十分钟轻松交流", "例如：每天留出十分鐘輕鬆交流"], goalDetailPlaceholder: ["记录要做什么、由谁陪伴、如何持续。", "記錄要做甚麼、由誰陪伴、如何持續。"], observations: ["工作人员私密观察", "工作人員私人觀察"], observationNote: ["仅授权工作人员可见，不用于 AI 报告生成。", "只供獲授權工作人員查看，不用於 AI 報告產生。"], observationBody: ["观察记录", "觀察記錄"], addObservation: ["添加观察", "新增觀察"], noObservations: ["暂无观察记录", "暫無觀察記錄"],
  scaleIntro: ["管理有来源、适用范围和版本记录的测评量表。", "管理具來源、適用範圍及版本記錄的評估量表。"], importScale: ["导入量表版本", "匯入量表版本"], downloadExample: ["下载演示定义", "下載示範定義"], definition: ["量表定义 JSON", "量表定義 JSON"], chooseFile: ["选择 JSON 文件", "選擇 JSON 檔案"], immutableNote: ["每次导入都创建不可变的新版本，既有测评与报告保留原版本。", "每次匯入都建立不可變的新版本，既有評估與報告保留原版本。"], validJSON: ["请输入有效的 JSON 对象。", "請輸入有效的 JSON 物件。"], scaleActive: ["可分配", "可分配"], retired: ["已停用", "已停用"], retire: ["停用此版本", "停用此版本"], retireTitle: ["停用量表版本", "停用量表版本"], retireNote: ["停用后将不再用于新的测评分配，既有数据仍保留。", "停用後將不再用於新的評估分配，既有資料仍保留。"], reactivate: ["重新启用此版本", "重新啟用此版本"], reactivateTitle: ["重新启用量表版本", "重新啟用量表版本"], reactivateNote: ["重新启用后可用于新的测评分配。服务器会核验当前建议内容是否仍匹配此量表；不匹配时无法启用，既有测评与报告不受影响。", "重新啟用後可用於新的評估分配。伺服器會核實目前建議內容是否仍配對此量表；不匹配時無法啟用，既有評估與報告不受影響。"], source: ["来源", "來源"], rights: ["授权说明", "授權說明"], suitable: ["适用年龄", "適用年齡"], roles: ["作答身份", "作答身分"], interval: ["重复测评间隔", "重複評估間隔"], days: ["天", "天"], noScales: ["暂无量表版本", "暫無量表版本"],
  contentIntro: ["建议内容与报告模板按版本保存，每次发布形成独立记录。", "建議內容與報告範本按版本儲存，每次發佈形成獨立記錄。"], advice: ["关怀建议", "關懷建議"], template: ["报告模板", "報告範本"], currentVersion: ["当前版本", "目前版本"], newVersion: ["新版本号", "新版本編號"], contentJson: ["内容 JSON", "內容 JSON"], saveVersion: ["保存新版本", "儲存新版本"], contentSaved: ["新内容版本已保存。", "新內容版本已儲存。"], versions: ["版本记录", "版本記錄"],
  inviteTitle: ["加入家庭支持空间", "加入家庭支援空間"], inviteWelcome: ["你已获邀请参与这个家庭的成长支持。请建立专属账户。", "你已獲邀請參與這個家庭的成長支援。請建立專屬帳戶。"], yourName: ["你的姓名", "你的姓名"], acceptInvite: ["接受邀请并创建账户", "接受邀請並建立帳戶"], noToken: ["此链接缺少邀请凭证，请使用完整的邀请链接。", "此連結缺少邀請憑證，請使用完整的邀請連結。"], invitation: ["家庭邀请", "家庭邀請"], returnLogin: ["返回登录", "返回登入"], unauthorized: ["当前账户无权访问此内容。", "目前帳戶無權存取此內容。"], missing: ["此记录不存在或你已失去访问权限。", "此記錄不存在或你已失去存取權限。"], openMenu: ["打开导航", "開啟導覽"], closeMenu: ["关闭导航", "關閉導覽"], skip: ["跳至主要内容", "跳至主要內容"], all: ["全部", "全部"], status: ["状态", "狀態"],
} as const;
export type CopyKey = keyof typeof dictionary;
export const copy = (locale: Locale) => (key: CopyKey): string => dictionary[key][locale === "zh-HK" ? 1 : 0];
export const roleName = (role: Role, locale: Locale) => ({ admin: ["管理员", "管理員"], staff: ["工作人员", "工作人員"], parent: ["家长", "家長"], student: ["学生", "學生"], teacher: ["教师", "教師"] }[role][locale === "zh-HK" ? 1 : 0]);
export const statusName = (status: AssessmentStatus, locale: Locale) => ({ pending: ["待作答", "待作答"], queued: ["报告生成中", "報告產生中"], published: ["已完成", "已完成"], failed: ["生成失败", "產生失敗"] }[status][locale === "zh-HK" ? 1 : 0]);
export function formatDate(value: string, locale: Locale, withTime = false): string { const date = new Date(value); return Number.isNaN(date.getTime()) ? value : new Intl.DateTimeFormat(locale, { year: "numeric", month: "short", day: "numeric", ...(withTime ? { hour: "2-digit", minute: "2-digit" } as const : {}) }).format(date); }
