"use client";
import { useState } from "react";
import { Check, Copy, LinkSimple, LockKey, ShieldCheck, Warning } from "@phosphor-icons/react";
import { api, apiUrl, eligibleScales, type Family, type Locale, type RecoveryTarget, type Role, type Scale, type Workspace } from "./api";
import { copy, formatDate, roleName } from "./copy";
import { Badge, ErrorNotice, Field, FormActions, Modal, useMutation } from "./ui";
interface FormProps { locale: Locale; onClose: () => void; onDone: () => Promise<void> }
export function FamilyForm({ locale, onClose, onDone, workspace }: FormProps & { workspace: Workspace }) {
  const t = copy(locale); const m = useMutation(); const [birthDate, setBirthDate] = useState("");
  const today = new Date(); const birth = new Date(birthDate); const age = birthDate ? today.getFullYear() - birth.getFullYear() - (today.getMonth() < birth.getMonth() || (today.getMonth() === birth.getMonth() && today.getDate() < birth.getDate()) ? 1 : 0) : null;
  return <Modal title={t("newFamily")} onClose={onClose} locale={locale}><form onSubmit={event => { event.preventDefault(); const values = Object.fromEntries(new FormData(event.currentTarget)); if (!values.assignedTo) delete values.assignedTo; void m.run(async () => { await api("/api/families", locale, { method: "POST", body: values }); await onDone(); }); }}><div className="form-grid"><Field label={t("familyName")}><input name="familyName" required maxLength={100} /></Field><Field label={t("child")}><input name="childName" required maxLength={80} /></Field><Field label={t("birthDate")}><input name="birthDate" type="date" required max={today.toISOString().slice(0,10)} value={birthDate} onChange={event => setBirthDate(event.target.value)} /></Field><Field label={t("age")}><input readOnly value={age === null || Number.isNaN(age) ? "—" : `${age} ${t("years")}`} /></Field><Field label={t("grade")}><input name="grade" required maxLength={50} /></Field><Field label={t("guardian")}><input name="guardianLabel" required maxLength={80} /></Field></div><Field label={t("staff")}><select name="assignedTo" defaultValue={workspace.user.role === "staff" ? workspace.user.id : ""}><option value="">{t("unassigned")}</option>{workspace.staff.map(person => <option key={person.id} value={person.id}>{person.name}</option>)}</select></Field><p className="form-note"><ShieldCheck size={18}/>{t("familyEmptyText")}</p>{m.error && <ErrorNotice locale={locale} message={m.error} />}<FormActions locale={locale} onClose={onClose} busy={m.busy} label="create" /></form></Modal>;
}
export function ConsentForm({ family, staff, locale, onClose, onDone, openPrivacy }: FormProps & { family: Family; staff: boolean; openPrivacy: () => void }) {
  const t = copy(locale); const m = useMutation(); const [accepted, setAccepted] = useState(false); const [aiProcessing, setAiProcessing] = useState(false);
  return <Modal title={t("consentTitle")} locale={locale} onClose={onClose}><form onSubmit={event => { event.preventDefault(); const data = new FormData(event.currentTarget); void m.run(async () => { await api(`/api/families/${encodeURIComponent(family.id)}/consent`, locale, { method: "POST", body: { accepted: true, aiProcessing, guardianName: data.get("guardianName"), ...(staff ? { reference: data.get("reference") } : {}) } }); await onDone(); }); }}><div className="info-strip"><ShieldCheck size={22}/><span>{t(staff ? "offlineConsent" : "directConsent")}</span></div><p className="body-copy">{t(staff ? "offlineNote" : "consentNote")}</p><button type="button" className="text-link" onClick={openPrivacy}>{t("privacy")}</button><Field label={t("guardian")}><input name="guardianName" defaultValue={family.guardianLabel} required maxLength={80} /></Field>{staff && <Field label={t("offlineRef")}><input name="reference" required minLength={3} maxLength={200} /></Field>}<label className="checkbox-label"><input type="checkbox" required checked={accepted} onChange={event => setAccepted(event.target.checked)} /><span>{t("consentCheck")}</span></label><label className="checkbox-label"><input type="checkbox" checked={aiProcessing} onChange={event => setAiProcessing(event.target.checked)} /><span>{t("aiConsent")}<small className="checkbox-hint">{t("aiConsentNote")}</small></span></label>{m.error && <ErrorNotice locale={locale} message={m.error} />}<FormActions locale={locale} busy={m.busy} onClose={onClose} label="submit" disabled={!accepted} /></form></Modal>;
}
export function InvitationForm({ family, locale, onClose, onDone }: FormProps & { family: Family }) {
  const t = copy(locale); const m = useMutation(); const [role, setRole] = useState<Role>("parent"); const [invitation, setInvitation] = useState<{ url: string; expiresAt: string } | null>(null); const [copied, setCopied] = useState(false);
  return <Modal title={t("invite")} onClose={onClose} locale={locale}><p className="body-copy">{t("inviteNote")}</p><form onSubmit={event => { event.preventDefault(); void m.run(async () => { setInvitation(await api(`/api/families/${encodeURIComponent(family.id)}/invites`, locale, { method: "POST", body: { role } })); setCopied(false); await onDone(); }); }}><Field label={t("roles")}><select value={role} onChange={event => { setRole(event.target.value as Role); setInvitation(null); }}>{(["parent", "student", "teacher"] as const).map(value => <option key={value} value={value}>{roleName(value, locale)}</option>)}</select></Field><button type="submit" className="button primary" disabled={m.busy}><LinkSimple />{t(m.busy ? "creating" : "createInvite")}</button>{m.error && <ErrorNotice locale={locale} message={m.error} />}</form>{invitation && <div className="invitation-result"><Badge tone="sage">{roleName(role, locale)} · {family.familyName}</Badge><Field label={t("inviteLink")}><input value={invitation.url} readOnly onFocus={event => event.target.select()} /></Field><p className="muted small-text">{t("expires")} {formatDate(invitation.expiresAt, locale, true)}</p><button className="button secondary" onClick={async () => { try { await navigator.clipboard.writeText(invitation.url); setCopied(true); } catch { m.setError(t("copyFailed")); } }}>{copied ? <Check /> : <Copy />}{t(copied ? "copied" : "copy")}</button></div>}</Modal>;
}
export function DeleteFamilyForm({ family, locale, onClose, onDone }: FormProps & { family: Family }) {
  const t = copy(locale); const m = useMutation(); const [confirmation, setConfirmation] = useState("");
  return <Modal title={t("deleteTitle")} onClose={onClose} locale={locale}><form onSubmit={event => { event.preventDefault(); void m.run(async () => { await api(`/api/families/${encodeURIComponent(family.id)}`, locale, { method: "DELETE", body: { confirmation } }); await onDone(); }); }}><div className="danger-note"><Warning size={26} /><p>{t("deleteWarning")}</p></div><p><strong>{family.familyName} · {family.childName}</strong></p><Field label={`${t("confirmName")}「${family.childName}」`}><input autoComplete="off" value={confirmation} onChange={event => setConfirmation(event.target.value)} required /></Field>{m.error && <ErrorNotice locale={locale} message={m.error} />}<div className="form-actions"><button type="button" className="button secondary" onClick={onClose} disabled={m.busy}>{t("cancel")}</button><button type="submit" className="button danger" disabled={m.busy || confirmation !== family.childName}>{t("deleteButton")}</button></div></form></Modal>;
}
export function AssessmentForm({ workspace, familyId, locale, onClose, onDone }: FormProps & { workspace: Workspace; familyId?: string }) {
  const t = copy(locale); const m = useMutation(); const [selectedFamily, setSelectedFamily] = useState(familyId || workspace.families[0]?.id || ""); const family = workspace.families.find(item => item.id === selectedFamily); const [memberId, setMemberId] = useState(""); const respondent = family?.members.find(item => item.id === memberId)?.id || family?.members[0]?.id || ""; const scales = eligibleScales(workspace.scales, family, respondent); const [version, setVersion] = useState(""); const scaleVersionId = scales.find(item => item.id === version)?.id || scales[0]?.id || "";
  return <Modal title={t("newAssessment")} locale={locale} onClose={onClose}><form onSubmit={event => { event.preventDefault(); void m.run(async () => { await api("/api/assessments", locale, { method: "POST", body: { familyId: selectedFamily, respondentId: respondent, scaleVersionId, locale } }); await onDone(); }); }}><Field label={t("chooseFamily")}><select required value={selectedFamily} onChange={event => { setSelectedFamily(event.target.value); setMemberId(""); setVersion(""); }}><option value="" disabled>{t("chooseFamily")}</option>{workspace.families.map(item => <option value={item.id} key={item.id}>{item.familyName} · {item.childName}</option>)}</select></Field><Field label={t("respondent")}><select required value={respondent} onChange={event => { setMemberId(event.target.value); setVersion(""); }}><option value="" disabled>{t("chooseMember")}</option>{family?.members.map(item => <option key={item.id} value={item.id}>{item.name} · {roleName(item.role, locale)}</option>)}</select></Field><Field label={t("scaleVersion")}><select required value={scaleVersionId} onChange={event => setVersion(event.target.value)}><option value="" disabled>{t("chooseScale")}</option>{scales.map(scale => <option key={scale.id} value={scale.id}>{scale.title} · v{scale.version}{scale.demo ? ` · ${t("demo")}` : ""}</option>)}</select></Field>{!scales.length && <p className="form-note">{t("noEligibleScale")}</p>}{family && !family.consent && <div className="warning-note"><ShieldCheck />{t("consentNeeded")}</div>}<p className="muted small-text">{t("retakeNote")}</p>{m.error && <ErrorNotice locale={locale} message={m.error} />}<FormActions locale={locale} onClose={onClose} busy={m.busy} label="newAssessment" disabled={!family?.consent || !scaleVersionId || !respondent} /></form></Modal>;
}
export function RecoveryForm({ member, locale, onClose }: { member: RecoveryTarget; locale: Locale; onClose: () => void }) {
  const t = copy(locale); const m = useMutation(); const [link, setLink] = useState<{ url: string; expiresAt: string } | null>(null); const [copied, setCopied] = useState(false);
  return <Modal title={t("issueRecovery")} onClose={onClose} locale={locale}><p className="body-copy">{t("recoveryNote")}</p><form onSubmit={event => { event.preventDefault(); void m.run(async () => { setLink(await api(`/api/users/${encodeURIComponent(member.memberId)}/recovery`, locale, { method: "POST", body: {} })); setCopied(false); }); }}><Field label={t("recoveryFor")}><input value={member.memberName} readOnly /></Field><button type="submit" className="button primary" disabled={m.busy}><LockKey />{t(m.busy ? "creating" : "createRecovery")}</button>{m.error && <ErrorNotice locale={locale} message={m.error} />}</form>{link && <div className="invitation-result"><Field label={t("recoveryLink")}><input value={link.url} readOnly onFocus={event => event.target.select()} /></Field><p className="muted small-text">{t("expires")} {formatDate(link.expiresAt, locale, true)}</p><button className="button secondary" onClick={async () => { try { await navigator.clipboard.writeText(link.url); setCopied(true); } catch { m.setError(t("copyFailed")); } }}>{copied ? <Check /> : <Copy />}{t(copied ? "copied" : "copy")}</button></div>}</Modal>;
}
export function GoalForm({ workspace, familyId, locale, onClose, onDone }: FormProps & { workspace: Workspace; familyId?: string }) { const t = copy(locale); const m = useMutation(); return <Modal title={t("newGoal")} onClose={onClose} locale={locale}><form onSubmit={event => { event.preventDefault(); const values = Object.fromEntries(new FormData(event.currentTarget)); void m.run(async () => { await api("/api/goals", locale, { method: "POST", body: values }); await onDone(); }); }}><Field label={t("family")}><select name="familyId" defaultValue={familyId || workspace.families[0]?.id || ""} required><option value="" disabled>{t("chooseFamily")}</option>{workspace.families.map(item => <option key={item.id} value={item.id}>{item.familyName}</option>)}</select></Field><Field label={t("goalTitle")}><input name="title" required maxLength={120} placeholder={t("goalPlaceholder")} /></Field><Field label={t("goalDetail")}><textarea name="detail" required maxLength={2000} rows={4} placeholder={t("goalDetailPlaceholder")} /></Field>{m.error && <ErrorNotice locale={locale} message={m.error} />}<FormActions locale={locale} onClose={onClose} busy={m.busy} label="create" /></form></Modal>; }
export function ObservationForm({ family, locale, onClose, onDone }: FormProps & { family: Family }) { const t = copy(locale); const m = useMutation(); return <Modal title={t("addObservation")} locale={locale} onClose={onClose}><form onSubmit={event => { event.preventDefault(); const data = new FormData(event.currentTarget); void m.run(async () => { await api("/api/observations", locale, { method: "POST", body: { familyId: family.id, body: data.get("body") } }); await onDone(); }); }}><p className="info-strip"><ShieldCheck />{t("observationNote")}</p><Field label={t("observationBody")}><textarea name="body" rows={6} required maxLength={5000} /></Field>{m.error && <ErrorNotice locale={locale} message={m.error} />}<FormActions locale={locale} onClose={onClose} busy={m.busy} /></form></Modal>; }
export function ScaleImportForm({ locale, onClose, onDone }: FormProps) { const t = copy(locale); const m = useMutation(); const [definition, setDefinition] = useState(""); return <Modal title={t("importScale")} locale={locale} onClose={onClose} wide><p className="body-copy">{t("immutableNote")}</p><a className="text-link" href={apiUrl("/api/scales/example", locale)} download>{t("downloadExample")}</a><form onSubmit={event => { event.preventDefault(); void m.run(async () => { let value: unknown; try { value = JSON.parse(definition); } catch { throw new Error(t("validJSON")); } if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error(t("validJSON")); await api("/api/scales", locale, { method: "POST", body: { definition: value } }); await onDone(); }); }}><Field label={t("chooseFile")}><input type="file" accept=".json,application/json" onChange={event => { const file = event.target.files?.[0]; if (file) void m.run(async () => { if (file.size > 2_000_000) throw new Error(locale === "zh-HK" ? "檔案須小於 2 MB。" : "文件须小于 2 MB。"); setDefinition(await file.text()); }); }} /></Field><Field label={t("definition")}><textarea className="code-input" value={definition} onChange={event => setDefinition(event.target.value)} required rows={15} spellCheck={false} /></Field>{m.error && <ErrorNotice locale={locale} message={m.error} />}<FormActions locale={locale} onClose={onClose} busy={m.busy} label="importScale" /></form></Modal>; }
export function RetireScaleForm({ scale, locale, onClose, onDone }: FormProps & { scale: Scale }) {
  const t = copy(locale); const m = useMutation(); const reactivate = scale.status === "retired";
  return <Modal title={t(reactivate ? "reactivateTitle" : "retireTitle")} onClose={onClose} locale={locale}><form onSubmit={event => { event.preventDefault(); void m.run(async () => { await api(`/api/scales/${encodeURIComponent(scale.id)}`, locale, { method: "PATCH", body: { status: reactivate ? "active" : "retired" } }); await onDone(); }); }}><p><strong>{scale.title} · v{scale.version}</strong></p><p className="body-copy">{t(reactivate ? "reactivateNote" : "retireNote")}</p>{m.error && <ErrorNotice locale={locale} message={m.error} />}<FormActions locale={locale} onClose={onClose} busy={m.busy} label={reactivate ? "reactivate" : "retire"} /></form></Modal>;
}
export function ReactivateScaleForm(props: FormProps & { scale: Scale }) { return <RetireScaleForm {...props} />; }
