"use client";
import { useEffect, useRef, useState } from "react";
import { ArrowRight, CircleNotch, IconContext, UserPlus } from "@phosphor-icons/react";
import { api, errorMessage, type Region, type Role, type Session } from "@/components/api";
import { formatDate, roleName } from "@/components/copy";
import { Brand, DemoBanner, ErrorNotice, Field, Loading, LocaleSwitch, PrivacyModal, RegionLabel, useLocale, useMutation } from "@/components/ui";
export default function InvitePage() {
  const { locale, setLocale, t } = useLocale(); const [token, setToken] = useState<string | null>(null); const [invite, setInvite] = useState<{ familyName: string; role: Role; region: Region; expiresAt: string } | null>(null); const [session, setSession] = useState<Session | null>(null); const [error, setError] = useState(""); const [privacy, setPrivacy] = useState(false); const m = useMutation(); const [attempt, setAttempt] = useState(0);
  const tokenRead = useRef(false);
  useEffect(() => { if (tokenRead.current) return; tokenRead.current = true; const fragment = new URLSearchParams(window.location.hash.slice(1)); const query = new URLSearchParams(window.location.search); setToken(fragment.get("token") || query.get("token") || ""); window.history.replaceState(null, "", window.location.pathname); }, []);
  useEffect(() => { if (token === null) return; if (!token) { setError(t("noToken")); return; } const controller = new AbortController(); setError(""); api<{ familyName: string; role: Role; region: Region; expiresAt: string }>("/api/invite", locale, { signal: controller.signal, headers: { "X-Invitation-Token": token } }).then(setInvite).catch(err => { if (!controller.signal.aborted) setError(errorMessage(err)); }); api<Session>("/api/session", locale, { signal: controller.signal }).then(value => { setSession(value); if (value.region === "HK" && !localStorage.getItem("nova-locale")) setLocale("zh-HK"); }).catch(() => undefined); return () => controller.abort(); }, [token, locale, attempt]);
  return <IconContext.Provider value={{ size: 20, weight: "regular" }}><main className="invite-page"><header className="login-header"><Brand /><div className="login-header-tools">{session && <RegionLabel session={session} locale={locale} />}<LocaleSwitch locale={locale} onChange={setLocale} /></div></header>{session?.mode === "demo" && <DemoBanner locale={locale} />}<section className="invite-card"><div className="login-card-icon"><UserPlus size={28} weight="duotone" /></div><span className="eyebrow">{t("invitation")}</span><h1>{t("inviteTitle")}</h1>{error ? <ErrorNotice message={error} locale={locale} onRetry={token ? () => setAttempt(attempt + 1) : undefined} /> : !invite ? <Loading locale={locale} /> : <><p>{t("inviteWelcome")}</p><div className="invite-summary"><strong>{invite.familyName}</strong><span>{roleName(invite.role, locale)} · {t(invite.region === "HK" ? "regionHK" : "regionCN")}</span><small>{t("expires")} {formatDate(invite.expiresAt, locale, true)}</small></div><form onSubmit={event => { event.preventDefault(); const data = new FormData(event.currentTarget); void m.run(async () => { await api("/api/invite", locale, { method: "POST", body: { token, name: data.get("name"), username: data.get("username"), password: data.get("password") } }); window.location.replace("/"); }); }}><Field label={t("yourName")}><input name="name" autoComplete="name" required maxLength={80} /></Field><Field label={t("username")} hint={t("usernameHint")}><input name="username" autoComplete="username" autoCapitalize="none" autoCorrect="off" required minLength={3} maxLength={100} /></Field><Field label={t("password")} hint={t("passwordHint")}><input name="password" type="password" autoComplete="new-password" required minLength={12} /></Field>{m.error && <ErrorNotice message={m.error} locale={locale} />}<button className="button primary full-width" disabled={m.busy}>{m.busy ? <CircleNotch className="spin" /> : <ArrowRight />}{t("acceptInvite")}</button></form></>}<button className="text-link login-privacy" onClick={() => setPrivacy(true)}>{t("privacy")}</button><a href="/" className="text-link">{t("returnLogin")}</a></section>{privacy && <PrivacyModal locale={locale} onClose={() => setPrivacy(false)} />}</main></IconContext.Provider>;
}
